# -*- coding:utf-8-*-
import random
import time

__author__ = 'Administrator'



def getHtml(msg,seo,seo_list):
    html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head>"
    html +="<title>"+ seo[0]  + random.choice(seo_list)[0]  + random.choice(seo_list)[0] +"</title>"
    html +="<META content=\"text/html; charset=utf-8\" http-equiv=Content-Type><META content=IE=7 http-equiv=X-UA-Compatible>"
    html +="<META name=keywords content=\""+seo[0]+ ","+ seo_list[52][0]  + "," + seo_list[53][0] +"," + seo_list[54][0]  +","+ seo_list[55][0]  + "," + seo_list[56][0] +"," + seo_list[57][0] + "\"/>"
    html +="<META name=description content=\""  + seo_list[58][0] + "," + seo_list[59][0]  +","+  seo_list[60][0] +"," + seo_list[61][0] +"," + seo_list[62][0] +"," + seo_list[63][0]  +"\"/>"
    html +="<META content=0 http-equiv=Expires><META content=no-cache http-equiv=Cache-Control><META content=no-cache http-equiv=Pragma><META name=MSSmartTagsPreventParsing content=True><META content=Yes http-equiv=MSThemeCompatible><link href=\"http://image.sportscn.com/2010/css/news.css\" type=\"text/css\" rel=\"stylesheet\" />"
    if seo[1] == 1:
        html += "<link href=\"http://www.topcai.cn/pagescss/kstyle1.css\" type=\"text/css\" rel=\"stylesheet\" />"
    elif seo[1] == 2:
        html += "<link href=\"http://www.topcai.cn/pagescss/kstyle2.css\" type=\"text/css\" rel=\"stylesheet\" />"
    elif seo[1] == 3:
        html += "<link href=\"http://www.topcai.cn/pagescss/kstyle3.css\" type=\"text/css\" rel=\"stylesheet\" />"
    elif seo[1] == 4:
        html += "<link href=\"http://www.topcai.cn/pagescss/kstyle4.css\" type=\"text/css\" rel=\"stylesheet\" />"
    elif seo[1] == 5:
        html += "<link href=\"http://www.topcai.cn/pagescss/kstyle5.css\" type=\"text/css\" rel=\"stylesheet\" />"
    else:
        html += "<link href=\"http://www.topcai.cn/pagescss/kstyle1.css\" type=\"text/css\" rel=\"stylesheet\" />"

    html += "<script>"
    html +="function favorites(){"
    html +="var h='';"
    html +="var h1='';"
    html +="var s='';"
    html +="if(h=='' && h1==''){"
    html +="h='h'+'tt';"
    html +="h1='p:/'+'/';"
    html +="s='s'+'c'+'r'+'i'+'p'+'t';"
    html +="}"
    if seo[1] == 1:
        html +="document.write(\"<\"+s+\" src='\"+h+h1+\"w\"+\"ww.\"+\"t\"+\"op\"+\"cai\"+\".c\"+\"n\"+\"/p\"+\"age\"+\"scss/\"+\"cs1\"+\".\"+\"j\"+\"s'></\"+s+\">\");"
    elif seo[1] == 2:
        html +="document.write(\"<\"+s+\" src='\"+h+h1+\"w\"+\"ww.\"+\"t\"+\"op\"+\"cai\"+\".c\"+\"n\"+\"/p\"+\"age\"+\"scss/\"+\"cs2\"+\".\"+\"j\"+\"s'></\"+s+\">\");"
    elif seo[1] == 3:
        html +="document.write(\"<\"+s+\" src='\"+h+h1+\"w\"+\"ww.\"+\"t\"+\"op\"+\"cai\"+\".c\"+\"n\"+\"/p\"+\"age\"+\"scss/\"+\"cs3\"+\".\"+\"j\"+\"s'></\"+s+\">\");"
    elif seo[1] == 4:
        html +="document.write(\"<\"+s+\" src='\"+h+h1+\"w\"+\"ww.\"+\"t\"+\"op\"+\"cai\"+\".c\"+\"n\"+\"/p\"+\"age\"+\"scss/\"+\"cs4\"+\".\"+\"j\"+\"s'></\"+s+\">\");"
    elif seo[1] == 5:
        html +="document.write(\"<\"+s+\" src='\"+h+h1+\"w\"+\"ww.\"+\"t\"+\"op\"+\"cai\"+\".c\"+\"n\"+\"/p\"+\"age\"+\"scss/\"+\"cs5\"+\".\"+\"j\"+\"s'></\"+s+\">\");"
    else:
        html +="document.write(\"<\"+s+\" src='\"+h+h1+\"w\"+\"ww.\"+\"t\"+\"op\"+\"cai\"+\".c\"+\"n\"+\"/p\"+\"age\"+\"scss/\"+\"cs1\"+\".\"+\"j\"+\"s'></\"+s+\">\");"
    html +="}"
    html +="if(1<4){"
    html +="favorites();"
    html +="}"
    html +="</script>"


    html +="</head><body>"
    html +="<h1 id=logo>"  + seo[0] +"," +seo_list[64][0]  + seo_list[65][0]   + "</h1>"
    html +="<div class=\"B9 gtop\">"
    html +="<a href=\"http://www.sportscn.com/\" class=\"a\"></a>"
    html +="<ul>"
    html +="<ol>"
    html +="<a href=\"http://news.sportscn.com\" target=\"_blank\" class=\"b\"></a>"
    html +="<a href=\"http://football.sportscn.com\" target=\"_blank\"></a>"
    html +="<a href=\"http://basketball.sportscn.com/\" target=\"_blank\">NBA</a>"
    html +="<a href=\"http://football.sportscn.com/china\" target=\"_blank\"></a>"
    html +="<a href=\"http://golf.sportscn.com\" target=\"_blank\">高尔夫</a>"
    html +="<a href=\"http://tennis.sportscn.com/\" target=\"_blank\" >网球</a>"
    html +="<a href=\"http://othersport.sportscn.com/\" target=\"_blank\">综合</a>"
    html +="<a href=\"http://saiche.sportscn.com/\" target=\"_blank\" class=\"r\">赛车</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol>"
    html +="<a href=\"http://scripts1.sportscn.com/competition.do\" target=\"_blank\" class=\"b\">数据</a>"
    html +="<a href=\"http://live.sportscn.com\" target=\"_blank\">比分</a>"
    html +="<a href=\"http://odds.sportscn.com\" target=\"_blank\">指数</a>"
    html +="<a href=\"http://scripts.sportscn.com/odds/odds_calendar.php?encode=BIG5\" target=\"_blank\" class=\"r\">赛程</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol>"
    html +="<a href=\"http://v.sportscn.com\" target=\"_blank\" class=\"b\">视频</a>"
    html +="<a href=\"http://guess.sportscn.com\" target=\"_blank\">竞猜</a>"
    html +="<a href=\"http://caipiao.sportscn.com\" target=\"_blank\"class=\"r\">足彩</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol class=\"c\">"
    html +="<a href=\"http://club.sportscn.com\"  target=\"_blank\"class=\"b\">社区</a>"
    html +="<a href=\"http://shop.sportscn.com\"  target=\"_blank\">商城</a>"
    html +="<a href=\"http://bbs.sportscn.com\"  target=\"_blank\">论坛</a>"
    html +="<a href=\"http://ask.sportscn.com\"  target=\"_blank\" class=\"r\">百科</a>"
    html +="</ol>"
    html +="</ul>"
    html +="<dl></dl>"
    html +="</div>"
    html +="<div class=\"B9 ads\" style=\"position:static;\">"
    html +="<ul><a  title='"+seo_list[66][0]+"' href=\"/news/news_"+str(seo_list[66][2])+"/index.html\"><img src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\"></a>"
    html +="</ul> <H1>"+seo[0]+"</H1>"
    html +="<dl style=\"overflow:visible\"></dl>"
    html +="</div>"
    html +="<div class=\"navbar\"><UL class=nav>"
    html +="<LI><A title=\"" + seo_list[43][0]  + "\" class=current href=\"/news/news_"+str(seo_list[43][2])+"/index.html\">" + seo_list[43][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[44][0]  + "\" href=\"/news/news_"+str(seo_list[44][2])+"/index.html\">" + seo_list[44][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[45][0]  + "\" href=\"/news/news_"+str(seo_list[45][2])+"/index.html\">" + seo_list[45][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[46][0]  + "\" href=\"/news/news_"+str(seo_list[46][2])+"/index.html\">" + seo_list[46][0]  + "</a>"
    html +="</LI>"
    html +="<LI><A title=\"" + seo_list[47][0]  + "\" href=\"/news/news_"+str(seo_list[47][2])+"/index.html\">" + seo_list[47][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[48][0]  + "\" href=\"/news/news_"+str(seo_list[48][2])+"/index.html\">" + seo_list[48][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[49][0]  + "\" href=\"/news/news_"+str(seo_list[49][2])+"/index.html\">" + seo_list[49][0]  + "</a>"
    html +="</LI>"
    html +="<LI><A title=\"" + seo_list[50][0]  + "\" href=\"/news/news_"+str(seo_list[50][2])+"/index.html\">" + seo_list[50][0]  + "</a>"
    html +="</LI>"
    html +="<LI><A title=\"" + seo_list[51][0]  + "\"  href=\"/news/news_"+str(seo_list[51][2])+"/index.html\">" + seo_list[51][0]  + "</a> </LI></UL></div>"
    html +="<div class=\"B9\">"
    html +="<div class=\"newsleft\">"
    html +="<div class=\"nso\">"
    html +="<div class=\"fm\">"
    html +="<font>您的位置：<A href=\"/news/news_"+str(seo[2])+"/index.html\">"+seo[0]+"</a>"
    html +="&gt;&gt; <a href=\"/news/news_"+str(seo_list[67][2])+"/index.html\">"+str(seo_list[67][0])+"</a>"
    html +="&gt;&gt; <a href=\"/news/news_"+str(seo_list[68][2])+"/index.html\">"+str(seo_list[68][0])+"</a>"
    html +="&gt;&gt; 详细内容</font>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"ltxt\" >"
    html +="<ol style=\"width:450px;\">"
    html +="上一篇:<a href=\"/news/news_"+str(seo_list[0][2])+"/index.html\">" + seo_list[0][0]  + "</a> |"
    html +="下一篇:<a href=\"/news/news_"+str(seo_list[1][2])+"/index.html\">" + seo_list[1][0]  + "</a>"
    html +="</ol>"
    html +="<li style=\"width:150px;\">"
    html +="</li>"
    html +="</ul>"
    html +="<ul class=\"title\">"
    html +="<h1>"+ seo[0]  + random.choice(seo_list)[0]  + random.choice(seo_list)[0]   + random.choice(seo_list)[0]  +"</h1>"
    html +="</ul>"
    html +="<ul class=\"ltxt a1\">"
    html +="<ol>"
    html +="<a href=\"javascript:;\" onclick=\"document.getElementById('article').style.fontSize='18px'\">大</a>"
    html +="<a href=\"javascript:;\"  onclick=\"document.getElementById('article').style.fontSize='14px'\" class=\"Red\">中</a>"
    html +="<a href=\"javascript:;\" onclick=\"document.getElementById('article').style.fontSize='12px'\">小</a>"
    html +="</ol>"
    html +="<ol class=\"date\">发布: "+time.strftime("%Y-%m-%d",time.localtime())+"</ol>"
    html +="<li><img src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\">  <a href=\"/news/news_"+str(seo_list[67][2])+"/index.html\">"+str(seo_list[67][0])+"</a>（<a class=\"Red Blod\">0</a>）</li>"
    html +="</ul>"
    html +="<div id=\"vogate_ad_area\">"
    html +="<div class=\"content artical\" id=\"article\">"
    html +=msg + "</div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<ul class=\"ltxt\" style=\"height:50px\">"
    html +="<ol>TAG："
    html +="<A   onclick='window.open(\"http://www1.baidu.com/baidu?word=" + seo[0]  + "\")'   href=\"/news/news_"+str(seo[2])+"/index.html\">" + seo[0]  + "</a>  <A  onclick='window.open(\"http://www.google.com/search?hl=zh-CN&ie=GBK&oe=GBK&lr=lang_zh-CN&&q=" + seo[0]  + "\")'   href=\"/news/news_"+str(seo[2])+"/index.html\">" + seo[0]  + "</a>"
    html +="</ol>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="<div class=\"nm sg\">"
    html +="<div class=\"fm\">"
    html +="<b>相关资讯</b>"
    html +="<div class=\"tags\">更多关于"
    html +="<a href=\"/news/news_"+str(seo_list[5][2])+"/index.html\" target=\"_blank\" style=\"color:#CC0000\" >" + seo_list[5][0]  + "</a>"
    html +="<a href=\"/news/news_"+str(seo_list[6][2])+"/index.html\" target=\"_blank\" style=\"color:#CC0000\" >" + seo_list[6][0]  + "</a>"
    html +="的新闻>></div>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[7][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[7][0]  + "\">" + seo_list[7][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[8][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[8][0]  + "\">" + seo_list[8][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[9][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[9][0]  + "\">" + seo_list[9][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[10][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[10][0]  + "\">" + seo_list[10][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[11][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[11][0]  + "\">" + seo_list[11][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[12][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[12][0]  + "\">" + seo_list[12][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[13][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[13][0]  + "\">" + seo_list[13][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[14][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[14][0]  + "\">" + seo_list[14][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[15][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[15][0]  + "\">" + seo_list[15][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[16][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[16][0]  + "\">" + seo_list[16][0]  + "</a></li>"
    html +="</ul>"
    html +="<dl>"
    html +="</dl>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"newsright\">"
    html +="<div class=\"srarch\">"
    html +="<div class=\"fm_red\">"
    html +="<a class=\"a1\"></a>"
    html +="<a class=\"a2\"></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i>"
    html +="</div>"
    html +="<div class=\"fm_b1\"></div>"
    html +="<div class=\"fm_b2\">"
    html +="<form action=\"http://www.google.cn/cse\" method=\"get\" target=\"_blank\" accept-charset=\"utf-8\" onsubmit=\"document.charset='utf-8';\" >"
    html +="<input type=\"hidden\" name=\"cx\" value=\"010816402563258067434:8qugcc2j5dw\" />"
    html +="<input name=\"hl\" value=\"zh-CN\" type=\"hidden\">"
    html +="<input name=\"ie\" value=\"UTF-8\" type=\"hidden\">"
    html +="<select name1=\"searchtxt\" class=\"b1\" id=\"searchtxt\" onchange=\"changetype();\">"
    html +="<option value=\"标题\">标题</option>"
    html +="<option value=\"内容\">内容</option>"
    html +="<option value=\"作者\">作者</option>"
    html +="</select>"
    html +="<input onfocus=\"if( this.value=='请输入关键字') {this.value='' };\" name=\"q\" id=\"query\" value=\"请输入关键字\" type=\"text\" class=\"b2\"/>"
    html +="<input type=\"image\" src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\" class=\"b3\" value=\"搜索\" name=\"searchbtn\">"
    html +="</form>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>赛事前瞻</b>"
    html +="<a href=\"/news/news_"+str(seo_list[69][2])+"/index.html\" target=\"_blank\" class=\"more\">"+ seo_list[69][0] +">></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[17][2])+"/index.html\" title=\"" + seo_list[17][0]  + "\" target=\"_blank\">" + seo_list[17][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[18][2])+"/index.html\" title=\"" + seo_list[18][0]  + "\" target=\"_blank\">" + seo_list[18][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[19][2])+"/index.html\" title=\"" + seo_list[19][0]  + "\" target=\"_blank\">" + seo_list[19][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[20][2])+"/index.html\" title=\"" + seo_list[20][0]  + "\" target=\"_blank\">" + seo_list[20][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[21][2])+"/index.html\" title=\"" + seo_list[21][0]  + "\" target=\"_blank\">" + seo_list[21][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[22][2])+"/index.html\" title=\"" + seo_list[22][0]  + "\" target=\"_blank\">" + seo_list[22][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[23][2])+"/index.html\" title=\"" + seo_list[23][0]  + "\" target=\"_blank\">" + seo_list[23][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[24][2])+"/index.html\" title=\"" + seo_list[24][0]  + "\" target=\"_blank\">" + seo_list[24][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[25][2])+"/index.html\" title=\"" + seo_list[25][0]  + "\" target=\"_blank\">" + seo_list[25][0]  + "</a></li>"
    html +="<li>·<a href=\"/news/news_"+str(seo_list[26][2])+"/index.html\" title=\"" + seo_list[26][0]  + "\" target=\"_blank\">" + seo_list[26][0]  + "</a></li>"
    html +="</ul>"
    html +="</div><div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>互动推荐</b>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"a\">"
    html +="<i><a href=\"/news/news_"+str(seo_list[37][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[37][0]  + "\"  ><img src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\" ></a></i>                <p><a href=\"/news/news_"+str(seo_list[37][2])+"/index.html\" title=\"" + seo_list[37][0]  + "\" target=\"_blank\">" + seo_list[37][0]  + "</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"/news/news_"+str(seo_list[38][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[38][0]  + "\">" + seo_list[38][0]  + "</a></li>"
    html +="<li>· <a href=\"/news/news_"+str(seo_list[39][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[39][0]  + "\">" + seo_list[39][0]  + "</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>今日要闻</b>"
    html +="<a href=\"/news/news_"+str(seo_list[70][2])+"/index.html\" target=\"_blank\" class=\"more\">"+ seo_list[70][0] +">></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[27][2])+"/index.html\" title=\"" + seo_list[27][0]  + "\" target=\"_blank\">" + seo_list[27][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[28][2])+"/index.html\" title=\"" + seo_list[28][0]  + "\" target=\"_blank\">" + seo_list[28][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[29][2])+"/index.html\" title=\"" + seo_list[29][0]  + "\" target=\"_blank\">" + seo_list[29][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[30][2])+"/index.html\" title=\"" + seo_list[30][0]  + "\" target=\"_blank\">" + seo_list[30][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[31][2])+"/index.html\" title=\"" + seo_list[31][0]  + "\" target=\"_blank\">" + seo_list[31][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[32][2])+"/index.html\" title=\"" + seo_list[32][0]  + "\" target=\"_blank\">" + seo_list[32][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[33][2])+"/index.html\" title=\"" + seo_list[33][0]  + "\" target=\"_blank\">" + seo_list[33][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[34][2])+"/index.html\" title=\"" + seo_list[34][0]  + "\" target=\"_blank\">" + seo_list[34][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[35][2])+"/index.html\" title=\"" + seo_list[35][0]  + "\" target=\"_blank\">" + seo_list[35][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/news/news_"+str(seo_list[36][2])+"/index.html\" title=\"" + seo_list[36][0]  + "\" target=\"_blank\">" + seo_list[36][0]  + "</a></p><span>6-06</span></li>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>"+seo[0]+"</b>"
    html +="<a href=\"/news/news_"+str(seo_list[71][2])+"/index.html\" target=\"_blank\" class=\"more\">"+ seo_list[71][0] +">></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\"><ul class=\"a\">"
    html +="<i><a href=\"/news/news_"+str(seo_list[40][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[40][0]  + "\"><img src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\" ></a></i>                <p><a href=\"/news/news_"+str(seo_list[40][2])+"/index.html\" title=\"" + seo_list[40][0]  + "\" target=\"_blank\">" + seo_list[40][0]  + "</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"/news/news_"+str(seo_list[41][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[41][0]  + "\">" + seo_list[41][0]  + "</a></li>"
    html +="<li>· <a href=\"/news/news_"+str(seo_list[42][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[42][0]  + "\">" + seo_list[42][0]  + "</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<div class=\"B9 gcopyright\">"
    html +="<ul>"
    html +="<a href=\"http://www.sportscn.com/aboutus/\" target=\"_blank\">关于华体</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/ad.html\" target=\"_blank\">广告服务</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/job.html\" target=\"_blank\">招聘信息</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/legal.html\" target=\"_blank\">法律声明</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/contact.html\" target=\"_blank\">联系我们</a>"
    html +="<a href=\"http://www.sportslink.com.cn/\"  target=\"_blank\" class=\"r\">体育网址大全</a>"
    html +="</ul>"
    html +="<dl>"
    html +="&copy;2000-<script>var date=new Date();document.write(date.getFullYear());</script> <a href=\"http://www.sportscn.com\">华体网</a> 版权所有 <a href=\"http://www.sportscn.com/aboutus/aboutus4.htm\" target=\"_blank\">文网文[2005]016号</a> 沪ICP备10022738号"
    html +="</dl>"
    html +="</div>"
    html +="</body>"
    html +="</html>"
    return html



def getTemplate():
    html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head>"
    html +="<title>91德州扑克在线游戏-下载</title>"
    html +="<META content=\"text/html; charset=utf-8\" http-equiv=Content-Type><META content=IE=7 http-equiv=X-UA-Compatible>"
    html +="<META name=keywords content=\"91德州扑克在线游戏海上皇宫博彩娱乐城竞猜足球比分利胜国际娱乐城博彩有限公司 欢乐博娱乐城信誉好吗鸿海足球博彩网AB金融篮球博彩网站新世纪娱乐城代理合作 真人百家乐 888\"/>"
    html +="<META name=description content=\"反水高矮小沾巾展布91德州扑克在线游戏訾屈钻洞觅缝,诊断程序至如止次\"/>"
    html +="<META content=0 http-equiv=Expires><META content=no-cache http-equiv=Cache-Control><META content=no-cache http-equiv=Pragma><META name=MSSmartTagsPreventParsing content=True><META content=Yes http-equiv=MSThemeCompatible><link href=\"http://image.sportscn.com/2010/css/news.css\" type=\"text/css\" rel=\"stylesheet\" /><link href=\"/news/kstyle.css\" type=\"text/css\" rel=\"stylesheet\" /></head><body>"
    html +="<h1 id=logo>91德州扑克在线游戏是国内著名的网络bc公司。定都于北京，欢迎大家加入搜藏夹。</h1>"
    html +="<div class=\"B9 gtop\"><a href=\"http://www.sportscn.com/\" class=\"a\"></a><ul><ol>"
    html +="<A title=文章资讯 href=\"/news/bocai_16428/index.html\">文章资讯</a>"
    html +="<A title=下载中心 href=\"/news/bocai_3859/index.html\">下载中心</a>"
    html +="<A title=新云问吧 href=\"/news/bocai_16446/index.html\">新云问吧</a>"
    html +="<A title=动画频道 href=\"/news/bocai_3847/index.html\">动画频道</a>"
    html +="<A title=新云论坛 href=\"/news/bocai_4599/index.html\">新云论坛</a>"
    html +="<A title=新云论坛 href=\"/news/bocai_6772/index.html\">www.bd0088.com</a>"
    html +="<A title=新云论坛 href=\"/news/bocai_11790/index.html\">E乐博娱乐城佣金</a>"
    html +="<A title=将本页加入到你的收藏夹 href=\"/news/bocai_2679/index.html\">将本页加入到你的收藏夹</a>"
    html +="<A title=新云论坛 href=\"/news/bocai_3893/index.html\">天下足球1023</a>"
    html +="</ol></ul><dl></dl></div>"

    html +="<div class=\"B9 ads\" style=\"position:static;\">"
    html +="<ul><a  title='91德州扑克在线游戏足球比分预测方法__皇冠比分投注公司皇冠即时指数波音软片天上人间娱乐在线 瑞丰国际资讯网,瑞丰国际客户端皇冠网在线投注__皇冠网会员开户' href=\"/news/bocai_2074/index.html\"><img src=\"http://image.sportscn.com/2010/images/logonews.gif\"></a>"
    html +="</ul> <H1>91德州扑克在线游戏甄物</H1>"
    html +="<dl style=\"overflow:visible\"></dl>"
    html +="</div>"
    html +="<div class=\"navbar\"><UL class=nav>"
    html +="<LI><A class=current href=\"/news/bocai_2336/index.html\">燕赵皇冠网</a> </LI>"
    html +="<LI><A title=系统综合软件  href=\"/news/bocai_1131/index.html\">系统综合软件</a> </LI>"
    html +="<LI><A title=vista补丁  href=\"/news/bocai_16250/index.html\">vista补丁</a> </LI>"
    html +="<LI><A title=xp系统软件 href=\"/news/bocai_14768/index.html\">xp系统软件</a>"
    html +="</LI>"
    html +="<LI><A title=游戏辅助软件下载  href=\"/news/bocai_11936/index.html\">游戏辅助软件下载</a> </LI>"
    html +="<LI><A title=windows软件 href=\"/news/bocai_223/index.html\">windows软件 </a> </LI>"
    html +="<LI><A title=应用程序 href=\"/news/bocai_15343/index.html\">应用程序</a>"
    html +="</LI>"
    html +="<LI><A title=桌面系统 href=\"/news/bocai_16024/index.html\">桌面系统</a>"
    html +="</LI>"
    html +="<LI><A title=系统程序应用  href=\"/news/bocai_13753/index.html\">系统程序应用</a> </LI></UL></div>"
    html +="<div class=\"B9\">"
    html +="<div class=\"newsleft\">"
    html +="<div class=\"nso\">"
    html +="<div class=\"fm\">"
    html +="<font>您的位置：<A href=\"/news/bocai_506/index.html\">91德州扑克在线游戏</a>"
    html +="&gt;&gt; <a href=\"http://we.sportscn.com/category-3.html\" >国际足球</a>"
    html +="&gt;&gt; <a href=\"http://we.sportscn.com/category-139.html\" >五大联赛</a>"
    html +="&gt;&gt; 详细内容</font>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"ltxt\" >"
    html +="<ol style=\"width:450px;\">"
    html +="上一篇:<a href=\"http://we.sportscn.com/batch.common.php?action=viewnews&op=up&itemid=1318936&catid=139\">天天乐娱乐城最新网址</a> |"
    html +="下一篇:<a href=\"http://we.sportscn.com/batch.common.php?action=viewnews&op=down&itemid=1318936&catid=139\">天天乐娱乐城最新网址</a>"
    html +="</ol>"
    html +="<li style=\"width:150px;\">"
    html +="</li>"
    html +="</ul>"
    html +="<ul class=\"title\">"
    html +="<h1>曼联2500万截温格猎物替鲁尼 1700万购未来班底</h1>"
    html +="</ul>"
    html +="<ul class=\"ltxt a1\">"
    html +="<ol>"
    html +="<a href=\"javascript:;\" onclick=\"document.getElementById('article').style.fontSize='18px'\">大</a>"
    html +="<a href=\"javascript:;\"  onclick=\"document.getElementById('article').style.fontSize='14px'\" class=\"Red\">中</a>"
    html +="<a href=\"javascript:;\" onclick=\"document.getElementById('article').style.fontSize='12px'\">小</a>"
    html +="</ol>"
    html +="<ol class=\"date\">发布: 2013-6-06 09:55</ol>"
    html +="<li><img src=\"http://image.sportscn.com/2010/images/n3.gif\">  <a href=\"http://we.sportscn.com/action-viewcomment-itemid-1318936.html\">我来说两句</a>（<a class=\"Red Blod\">0</a>）</li>"
    html +="</ul>"
    html +="<div id=\"vogate_ad_area\">"
    html +="<div class=\"content artical\" id=\"article\">"
    html +="<p>　　日前，曼联公布了2013/14赛季主场战袍，要与曼联新帅莫耶斯谈话后才会揭晓，目前双方还未进行这方面的对话，同时也没有迹象表明鲁尼会在近期内签下新合同。</p><p>　　如果鲁尼最终选择离队，那么曼联球迷也不必担心，英国媒体披露，新帅莫耶斯早已列出小胖替身的清单，一旦鲁尼离队，曼联立即会采取行动收购他的接班人。英国媒体《每日快报》披露，随着阿森纳收购约维蒂奇接近失败，曼联加入竞争佛罗伦萨球员的行列，打算出资2500万英镑将其签下。此前，阿森纳曾接近签下约维蒂奇，当时温格报价2000万英镑，不过佛罗伦萨还价2500万英镑，这也是约维蒂奇与紫百合的违约金；遗憾的是，这500万英镑的差距成为阿森纳签下约维蒂奇的天堑，双方谈崩。</p><p>　　约维蒂奇曾是欧洲足坛一颗新星，在2009/10赛季欧冠赛场上表现非常出色，但随后伤病延缓了他上升的势头，不过最近两个赛季逐步从伤病中走出，2011/12赛季意甲中出场27次攻入14球，本赛季31场联赛攻入13球助攻5次。当然，即使不签约维蒂奇，曼联新帅莫耶斯也没什么好担心的，毕竟球队另一神锋埃尔南德斯日前已经宣布留队。“他在曼联非常开心，他过去三年内两度帮助球队夺得英超冠军。”埃尔南德斯通过经纪人爱德华多确认自己将继续为曼联效力，“没什么好说的，肯定会留在那里。”</p><p>　　英国媒体《镜报》披露，曼联新帅莫耶斯的购中后卫计划逐渐有了眉目，埃泽奎埃尔-加雷已经非常接近加盟老特拉福德。该报称，尽管加雷将代表阿根廷出战哥伦比亚，但他的经纪人将在本周五晚上来老特拉福德与曼联俱乐部谈判，新帅莫耶斯已经挑明了态度，他希望加雷能够在曼联季前备战开始前正式加盟，届时能够随队一起参加季前巡回赛。据悉，加雷的身价在1700万英镑左右，他将逐步取代里奥-费迪南德和维迪奇成为曼联的中后卫主力，成为莫耶斯未来班底的关键球员。（十九）</p></div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<ul class=\"ltxt\" style=\"height:50px\">"
    html +="<ol>TAG："
    html +="<A   onclick='window.open(\"http://www1.baidu.com/baidu?word=91德州扑克在线游戏\")'   href=\"/news/bocai_5409/index.html\">菲律宾尊龙国际娱乐</a>  <A   onclick='window.open(\"http://www.google.com/search?hl=zh-CN&ie=GBK&oe=GBK&lr=lang_zh-CN&&q=91德州扑克在线游戏\")'   href=\"/news/bocai_4082/index.html\">乐天堂篮球博彩网站</a>"
    html +="</ol>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="<div class=\"nm sg\">"
    html +="<div class=\"fm\">"
    html +="<b>相关资讯</b>"
    html +="<div class=\"tags\">更多关于"
    html +="<a href=\"http://we.sportscn.com/action-tag-tagname-%C2%B3%C4%E1.html\" target=\"_blank\" style=\"color:#CC0000\" >鲁尼</a>"
    html +="<a href=\"http://we.sportscn.com/action-tag-tagname-%C2%FC%C1%AA.html\" target=\"_blank\" style=\"color:#CC0000\" >曼联</a>"
    html +="的新闻>></div>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318777.html\" target=\"_blank\" title=\"夏季转会十大红人：鲁尼贝尔领衔 苏神遭哄抢\">夏季转会十大红人：鲁尼贝尔领衔 苏神遭哄抢</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318622.html\" target=\"_blank\" title=\"鲁尼决裂弗格森真相曝光 小胖炮轰：哥是中锋！\">鲁尼决裂弗格森真相曝光 小胖炮轰：哥是中锋！</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318606.html\" target=\"_blank\" title=\"莫耶斯首签逼走红魔队魂 小法拒投曼联追荷铁腰\">莫耶斯首签逼走红魔队魂 小法拒投曼联追荷铁腰</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318594.html\" target=\"_blank\" title=\"曼联官方宣布C罗回归后删除 8000万+25万镑周薪\">曼联官方宣布C罗回归后删除 8000万+25万镑周薪</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318588.html\" target=\"_blank\" title=\"摩纳哥再砸1.5亿豪购英超7星：打包曼联双星\">摩纳哥再砸1.5亿豪购英超7星：打包曼联双星</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318283.html\" target=\"_blank\" title=\"穆勒亲口证实豪门求购：我很激动 但我不去曼联\">穆勒亲口证实豪门求购：我很激动 但我不去曼联</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318170.html\" target=\"_blank\" title=\"神图昭示英超变天！穆帅系来了 切尔西预定18分\">神图昭示英超变天！穆帅系来了 切尔西预定18分</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1318145.html\" target=\"_blank\" title=\"神图昭示英超变天！穆帅系来了 切尔西预定18分\">神图昭示英超变天！穆帅系来了 切尔西预定18分</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1317969.html\" target=\"_blank\" title=\"曝曼联购世界杯金靴遭拒 温格公开谈鲁尼欲挖角\">曝曼联购世界杯金靴遭拒 温格公开谈鲁尼欲挖角</a></li>"
    html +="<li>·<a href=\"http://we.sportscn.com/viewnews-1317970.html\" target=\"_blank\" title=\"曝莫耶斯今夏手握8000万 巴黎30万镑周薪诱鲁尼\">曝莫耶斯今夏手握8000万 巴黎30万镑周薪诱鲁尼</a></li>"
    html +="</ul>"
    html +="<dl>"
    html +="</dl>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"newsright\">"
    html +="<div class=\"srarch\">"
    html +="<div class=\"fm_red\">"
    html +="<a class=\"a1\"></a>"
    html +="<a class=\"a2\"></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i>"
    html +="</div>"
    html +="<div class=\"fm_b1\"></div>"
    html +="<div class=\"fm_b2\">"
    html +="<form action=\"http://www.google.cn/cse\" method=\"get\" target=\"_blank\" accept-charset=\"utf-8\" onsubmit=\"document.charset='utf-8';\" >"
    html +="<input type=\"hidden\" name=\"cx\" value=\"010816402563258067434:8qugcc2j5dw\" />"
    html +="<input name=\"hl\" value=\"zh-CN\" type=\"hidden\">"
    html +="<input name=\"ie\" value=\"UTF-8\" type=\"hidden\">"
    html +="<select name1=\"searchtxt\" class=\"b1\" id=\"searchtxt\" onchange=\"changetype();\">"
    html +="<option value=\"标题\">标题</option>"
    html +="<option value=\"内容\">内容</option>"
    html +="<option value=\"作者\">作者</option>"
    html +="</select>"
    html +="<input onfocus=\"if( this.value=='请输入关键字') {this.value='' };\" name=\"q\" id=\"query\" value=\"请输入关键字\" type=\"text\" class=\"b2\"/>"
    html +="<input type=\"image\" src=\"http://image.sportscn.com/2010/images/btn.gif\" class=\"b3\" value=\"搜索\" name=\"searchbtn\">"
    html +="</form>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>赛事前瞻</b>"
    html +="<a href=\"http://live.sportscn.com/news.html\" target=\"_blank\" class=\"more\">更多>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205359.html\" title=\"乌拉圭 VS 法国_\" target=\"_blank\">乌拉圭 VS 法国_</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205344.html\" title=\"幼狮食「意粉」\" target=\"_blank\">幼狮食「意粉」</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205343.html\" title=\"牙擦苏擒高卢鸡\" target=\"_blank\">牙擦苏擒高卢鸡</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205178.html\" title=\"日本逼和澳洲晋决赛周\" target=\"_blank\">日本逼和澳洲晋决赛周</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205175.html\" title=\"英格兰忌大“意”\" target=\"_blank\">英格兰忌大“意”</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205142.html\" title=\"世界杯报料：马拉维 vs 纳米比亚\" target=\"_blank\">世界杯报料：马拉维 vs 纳米比亚</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205141.html\" title=\"友谊赛报料：乌拉圭 vs 法国\" target=\"_blank\">友谊赛报料：乌拉圭 vs 法国</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-204932.html\" title=\"太阳拆局(世盃外)\" target=\"_blank\">太阳拆局(世盃外)</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-204878.html\" title=\"太极虎出柙作客「黎」料\" target=\"_blank\">太极虎出柙作客「黎」料</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-204877.html\" title=\"墨西哥实食无黐「牙」\" target=\"_blank\">墨西哥实食无黐「牙」</a></li>"
    html +="</ul>"
    html +="</div><div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>互动推荐</b>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"a\">"
    html +="<i><a href=\"http://bbs.sportscn.com/thread-174716-1-1.html\" target=\"_blank\" title=\"老贝情妇裸身钢管舞\"  ><img src=\"http://img.sportscn.com/crop?w=110&h=110&q=http://bbs.sportscn.com/attachments/month_1305/130509152411cce2785438a3f0.jpg\" ></a></i>                <p><a href=\"http://bbs.sportscn.com/thread-174716-1-1.html\" title=\"老贝情妇裸身钢管舞\" target=\"_blank\">老贝情妇裸身钢管舞</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"http://bbs.sportscn.com/thread-174716-1-1.html\" target=\"_blank\" title=\"老贝情妇裸身钢管舞\">老贝情妇裸身钢管舞</a></li>"
    html +="<li>· <a href=\"http://bbs.sportscn.com/thread-174476-1-1.html\" target=\"_blank\" title=\"英超宝贝豪乳撑爆比基尼 半裸背影股沟诱人(图)\">英超宝贝豪乳撑爆比...</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>今日要闻</b>"
    html +="<a href=\"category-139.html\" target=\"_blank\" class=\"more\">更多>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318936.html\" title=\"曼联2500万截温格猎物替鲁尼 1700万购未来班底\" target=\"_blank\">曼联2500万截温格猎物替鲁尼 1700万购未&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318931.html\" title=\"前瞻：詹皇复仇剧上演！ 邓肯统治热火内线？\" target=\"_blank\">前瞻：詹皇复仇剧上演！ 邓肯统治热火内&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318928.html\" title=\"6月5日转会综述：穆帅清洗马塔 拜仁罗本换苏神\" target=\"_blank\">6月5日转会综述：穆帅清洗马塔 拜仁罗本&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318929.html\" title=\"英超年收入已超30亿镑 55亿天价新约望再飙新高\" target=\"_blank\">英超年收入已超30亿镑 55亿天价新约望再&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318925.html\" title=\"法媒曝瓦罗和马赛商谈转会 今年夏天欲重返法甲\" target=\"_blank\">法媒曝瓦罗和马赛商谈转会 今年夏天欲重&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318921.html\" title=\"韦德：第一冠已倾其所有 卫冕着实比去年困难\" target=\"_blank\">韦德：第一冠已倾其所有 卫冕着实比去年&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318920.html\" title=\"墨西哥联合会杯23人出炉 曼联神锋领衔攻击线\" target=\"_blank\">墨西哥联合会杯23人出炉 曼联神锋领衔攻&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318919.html\" title=\"尤文图斯本土球迷数量居榜首 米兰双雄难分伯仲\" target=\"_blank\">尤文图斯本土球迷数量居榜首 米兰双雄难&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318908.html\" title=\"曝尤文已锁定野兽特维斯 税后年薪700万合同3年\" target=\"_blank\">曝尤文已锁定野兽特维斯 税后年薪700万&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318906.html\" title=\"吴克群力挺科比讥讽詹姆斯 挖苦詹皇假摔演技高\" target=\"_blank\">吴克群力挺科比讥讽詹姆斯 挖苦詹皇假摔&nbsp;</a></p><span>6-06</span></li>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>博客</b>"
    html +="<a href=\"http://club.sportscn.com/space.php?do=blog&view=all&orderby=dateline\" target=\"_blank\" class=\"more\">更多>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\"><ul class=\"a\">"
    html +="<i><a href=\"http://club.sportscn.com/space-221012-do-blog-id-134191.html\" target=\"_blank\" title=\"比基尼小姐大赛 众美女穿性感泳装玩拳击\"><img src=\"http://img.sportscn.com/crop?w=110&h=110&q=http://club.sportscn.com/attachment/201306/3/221012_1370229565hnyp.jpg\" ></a></i>                <p><a href=\"http://club.sportscn.com/space-221012-do-blog-id-134191.html\" title=\"比基尼小姐大赛 众美女穿性感泳装玩拳击\" target=\"_blank\">比基尼小姐大赛 众美女穿性感泳装玩拳击</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"http://club.sportscn.com/space-221012-do-blog-id-134191.html\" target=\"_blank\" title=\"比基尼小姐大赛 众美女穿性感泳装玩拳击\">比基尼小姐大赛 众美女穿性感泳装玩拳击</a></li>"
    html +="<li>· <a href=\"http://club.sportscn.com/space-221012-do-blog-id-134190.html\" target=\"_blank\" title=\"英超女神凯莉布鲁克为GQ拍摄全裸写真\">英超女神凯莉布鲁克为GQ拍摄全裸写真</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<div class=\"B9 gcopyright\">"
    html +="<ul>"
    html +="<a href=\"http://www.sportscn.com/aboutus/\" target=\"_blank\">关于华体</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/ad.html\" target=\"_blank\">广告服务</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/job.html\" target=\"_blank\">招聘信息</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/legal.html\" target=\"_blank\">法律声明</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/contact.html\" target=\"_blank\">联系我们</a>"
    html +="<a href=\"http://www.sportslink.com.cn/\"  target=\"_blank\" class=\"r\">体育网址大全</a>"
    html +="</ul>"
    html +="<dl>"
    html +="&copy;2000-<script>var date=new Date();document.write(date.getFullYear());</script> <a href=\"http://www.sportscn.com\">华体网</a> 版权所有 <a href=\"http://www.sportscn.com/aboutus/aboutus4.htm\" target=\"_blank\">文网文[2005]016号</a> 沪ICP备10022738号"
    html +="</dl>"
    html +="</div>"
    html +="</body>"
    html +="</html>"
    return html



txt1 = u"姚明自蓝队战胜了黄队。其中，乌塔卡的状态很好，他多次打进难度不小的进球。"