# -*- coding:utf-8-*-
import random
import time

__author__ = 'Administrator'



def getHtml(msg,seo,seo_list):
    html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head>"
    html +="<title>"+ seo[0] + "</title>"
    html +="<META name=keywords content=\"比分网 华体比分直播\"/>"
    html +="<META name=description content=\"比分网 华体比分直播\"/>"
    html +="<META content=\"text/html; charset=utf-8\" http-equiv=Content-Type><META content=IE=7 http-equiv=X-UA-Compatible>"
    html +="<META content=0 http-equiv=Expires><META content=no-cache http-equiv=Cache-Control><META content=no-cache http-equiv=Pragma><META name=MSSmartTagsPreventParsing content=True><META content=Yes http-equiv=MSThemeCompatible><link href=\"http://image.sportscn.com/2010/css/news.css\" type=\"text/css\" rel=\"stylesheet\" />"
    html += "<link href=\"http://www.topcai.cn/pagescss/kstyle1.css\" type=\"text/css\" rel=\"stylesheet\" />"
    html +="<style type=\"text/css\">"
    html +=".zxgx li { display:block; height:auto;line-height:23px; border-bottom:solid 1px #e6e6e6;font-family:'宋体';}"
    html +=".sg .fm_b2 ul {width:600px; float:left; margin-top:10px;}"
    html +="</style>"
    html +="</head><body>"
    html +="</head><body>"
    html +="<h1 id=logo>"  + seo[0] + "</h1>"
    html +="<div class=\"B9 gtop\">"
    html +="<a href=\"http://www.sportscn.com/\" class=\"a\"></a>"
    html +="<ul>"
    html +="<ol>"
    html +="<a href=\"http://news.sportscn.com\" target=\"_blank\" class=\"b\"></a>"
    html +="<a href=\"http://football.sportscn.com\" target=\"_blank\"></a>"
    html +="<a href=\"http://basketball.sportscn.com/\" target=\"_blank\">NBA</a>"
    html +="<a href=\"http://football.sportscn.com/china\" target=\"_blank\"></a>"
    html +="<a href=\"http://golf.sportscn.com\" target=\"_blank\">高尔夫</a>"
    html +="<a href=\"http://tennis.sportscn.com/\" target=\"_blank\" >网球</a>"
    html +="<a href=\"http://othersport.sportscn.com/\" target=\"_blank\">综合</a>"
    html +="<a href=\"http://saiche.sportscn.com/\" target=\"_blank\" class=\"r\">赛车</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol>"
    html +="<a href=\"http://scripts1.sportscn.com/competition.do\" target=\"_blank\" class=\"b\">数据</a>"
    html +="<a href=\"http://live.sportscn.com\" target=\"_blank\">比分</a>"
    html +="<a href=\"http://odds.sportscn.com\" target=\"_blank\">指数</a>"
    html +="<a href=\"http://scripts.sportscn.com/odds/odds_calendar.php?encode=BIG5\" target=\"_blank\" class=\"r\">赛程</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol>"
    html +="<a href=\"http://v.sportscn.com\" target=\"_blank\" class=\"b\">视频</a>"
    html +="<a href=\"http://guess.sportscn.com\" target=\"_blank\">竞猜</a>"
    html +="<a href=\"http://caipiao.sportscn.com\" target=\"_blank\"class=\"r\">足彩</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol class=\"c\">"
    html +="<a href=\"http://club.sportscn.com\"  target=\"_blank\"class=\"b\">社区</a>"
    html +="<a href=\"http://shop.sportscn.com\"  target=\"_blank\">商城</a>"
    html +="<a href=\"http://bbs.sportscn.com\"  target=\"_blank\">论坛</a>"
    html +="<a href=\"http://ask.sportscn.com\"  target=\"_blank\" class=\"r\">百科</a>"
    html +="</ol>"
    html +="</ul>"
    html +="<dl></dl>"
    html +="</div>"
    
    html +="<div class=\"navbar\"><UL class=nav>"
    html +="<LI><A title=\"" + seo_list[43][0]  + "\" class=current href=\"/data/news_"+str(seo_list[43][2])+"/index.html\">" + seo_list[43][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[44][0]  + "\" href=\"/data/news_"+str(seo_list[44][2])+"/index.html\">" + seo_list[44][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[45][0]  + "\" href=\"/data/news_"+str(seo_list[45][2])+"/index.html\">" + seo_list[45][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[46][0]  + "\" href=\"/data/news_"+str(seo_list[46][2])+"/index.html\">" + seo_list[46][0]  + "</a>"
    html +="</LI>"
    html +="<LI><A title=\"" + seo_list[47][0]  + "\" href=\"/data/news_"+str(seo_list[47][2])+"/index.html\">" + seo_list[47][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[48][0]  + "\" href=\"/data/news_"+str(seo_list[48][2])+"/index.html\">" + seo_list[48][0]  + "</a> </LI>"
    html +="<LI><A title=\"" + seo_list[49][0]  + "\" href=\"/data/news_"+str(seo_list[49][2])+"/index.html\">" + seo_list[49][0]  + "</a>"
    html +="</LI>"
    html +="<LI><A title=\"" + seo_list[50][0]  + "\" href=\"/data/news_"+str(seo_list[50][2])+"/index.html\">" + seo_list[50][0]  + "</a>"
    html +="</LI>"
    html +="<LI><A title=\"" + seo_list[51][0]  + "\"  href=\"/data/news_"+str(seo_list[51][2])+"/index.html\">" + seo_list[51][0]  + "</a> </LI></UL></div>"
    html +="<div class=\"B9\">"
    html +="<div class=\"newsleft\">"
    html +="<div class=\"nso\">"
    html +="<div class=\"fm\">"
    html +="<font>您的位置：<A href=\"/data/news_"+str(seo[2])+"/index.html\">比分网</a>"
    html +="&gt;&gt; <a href=\"/data/news_"+str(seo_list[67][2])+"/index.html\">华体比分直播</a>"
    html +="&gt;&gt; <a href=\"/data/news_"+str(seo_list[68][2])+"/index.html\">"+str(seo_list[68][0])+"</a>"
    html +="&gt;&gt; 详细内容</font>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"ltxt\" >"
    html +="<ol style=\"width:450px;\">"
    html +="上一篇:<a href=\"/data/news_"+str(seo_list[0][2])+"/index.html\">" + seo_list[0][0]  + "</a> |"
    html +="下一篇:<a href=\"/data/news_"+str(seo_list[1][2])+"/index.html\">" + seo_list[1][0]  + "</a>"
    html +="</ol>"
    html +="<li style=\"width:150px;\">"
    html +="</li>"
    html +="</ul>"
    html +="<ul class=\"title\">"
    html +="<h1>"+ seo[0]  +"</h1>"
    html +="</ul>"
    html +="<ul class=\"ltxt a1\">"
    html +="<ol>"
    html +="<a href=\"javascript:;\" onclick=\"document.getElementById('article').style.fontSize='18px'\">大</a>"
    html +="<a href=\"javascript:;\"  onclick=\"document.getElementById('article').style.fontSize='14px'\" class=\"Red\">中</a>"
    html +="<a href=\"javascript:;\" onclick=\"document.getElementById('article').style.fontSize='12px'\">小</a>"
    html +="</ol>"
    html +="<ol class=\"date\">发布: "+time.strftime("%Y-%m-%d",time.localtime())+"</ol>"
    html +="<li> <a href=\"/data/news_"+str(seo_list[67][2])+"/index.html\">"+str(seo_list[67][0])+"</a>（<a class=\"Red Blod\">0</a>）</li>"
    html +="</ul>"
    html +="<div id=\"vogate_ad_area\">"
    html +="<div class=\"content artical\" id=\"article\">"
    html +=msg + "</div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<ul class=\"ltxt\" style=\"height:50px\">"
    html +="<ol>TAG："
    html +="<A   onclick='window.open(\"http://www1.baidu.com/baidu?word=比分网\")'   href=\"/data/news_"+str(seo[2])+"/index.html\">比分网</a>  <A  onclick='window.open(\"http://www.google.com/search?hl=zh-CN&ie=GBK&oe=GBK&lr=lang_zh-CN&&q=比分网\")'   href=\"/data/news_"+str(seo[2])+"/index.html\">比分网</a>"
    html +="</ol>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="<div class=\"nm sg\">"
    html +="<div class=\"fm\">"
    html +="<b>相关资讯</b>"
    html +="<div class=\"tags\">更多关于"
    html +="<a href=\"/data/news_"+str(seo_list[5][2])+"/index.html\" target=\"_blank\" style=\"color:#CC0000\" >" + '比分网'  + "</a>"
    html +="<a href=\"/data/news_"+str(seo_list[6][2])+"/index.html\" target=\"_blank\" style=\"color:#CC0000\" >" + '华体比分直播'  + "</a>"
    html +="的新闻>></div>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[7][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[7][0]  + "\">" + seo_list[7][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[8][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[8][0]  + "\">" + seo_list[8][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[9][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[9][0]  + "\">" + seo_list[9][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[10][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[10][0]  + "\">" + seo_list[10][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[11][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[11][0]  + "\">" + seo_list[11][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[12][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[12][0]  + "\">" + seo_list[12][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[13][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[13][0]  + "\">" + seo_list[13][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[14][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[14][0]  + "\">" + seo_list[14][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[15][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[15][0]  + "\">" + seo_list[15][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[16][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[16][0]  + "\">" + seo_list[16][0]  + "</a></li>"
    html +="</ul>"
    html +="<dl>"
    html +="</dl>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"newsright\">"
    html +="<div class=\"srarch\">"
    html +="<div class=\"fm_red\">"
    html +="<a class=\"a1\"></a>"
    html +="<a class=\"a2\"></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i>"
    html +="</div>"
    html +="<div class=\"fm_b1\"></div>"
    html +="<div class=\"fm_b2\">"
    html +="<form action=\"http://www.google.cn/cse\" method=\"get\" target=\"_blank\" accept-charset=\"utf-8\" onsubmit=\"document.charset='utf-8';\" >"
    html +="<input type=\"hidden\" name=\"cx\" value=\"010816402563258067434:8qugcc2j5dw\" />"
    html +="<input name=\"hl\" value=\"zh-CN\" type=\"hidden\">"
    html +="<input name=\"ie\" value=\"UTF-8\" type=\"hidden\">"
    html +="<select name1=\"searchtxt\" class=\"b1\" id=\"searchtxt\" onchange=\"changetype();\">"
    html +="<option value=\"标题\">标题</option>"
    html +="<option value=\"内容\">内容</option>"
    html +="<option value=\"作者\">作者</option>"
    html +="</select>"
    html +="<input onfocus=\"if( this.value=='请输入关键字') {this.value='' };\" name=\"q\" id=\"query\" value=\"请输入关键字\" type=\"text\" class=\"b2\"/>"
    html +="<input type=\"submit\"  class=\"b3\" value=\"搜索\" name=\"searchbtn\">"
    html +="</form>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>赛事前瞻</b>"
    html +="<a href=\"/data/news_"+str(seo_list[69][2])+"/index.html\" target=\"_blank\" class=\"more\">>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[17][2])+"/index.html\" title=\"" + seo_list[17][0]  + "\" target=\"_blank\">" + seo_list[17][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[18][2])+"/index.html\" title=\"" + seo_list[18][0]  + "\" target=\"_blank\">" + seo_list[18][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[19][2])+"/index.html\" title=\"" + seo_list[19][0]  + "\" target=\"_blank\">" + seo_list[19][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[20][2])+"/index.html\" title=\"" + seo_list[20][0]  + "\" target=\"_blank\">" + seo_list[20][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[21][2])+"/index.html\" title=\"" + seo_list[21][0]  + "\" target=\"_blank\">" + seo_list[21][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[22][2])+"/index.html\" title=\"" + seo_list[22][0]  + "\" target=\"_blank\">" + seo_list[22][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[23][2])+"/index.html\" title=\"" + seo_list[23][0]  + "\" target=\"_blank\">" + seo_list[23][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[24][2])+"/index.html\" title=\"" + seo_list[24][0]  + "\" target=\"_blank\">" + seo_list[24][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[25][2])+"/index.html\" title=\"" + seo_list[25][0]  + "\" target=\"_blank\">" + seo_list[25][0]  + "</a></li>"
    html +="<li>·<a href=\"/data/news_"+str(seo_list[26][2])+"/index.html\" title=\"" + seo_list[26][0]  + "\" target=\"_blank\">" + seo_list[26][0]  + "</a></li>"
    html +="</ul>"
    html +="</div><div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>互动推荐</b>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"a\">"
    html +="<i><a href=\"/data/news_"+str(seo_list[37][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[37][0]  + "\"  ><img src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\" ></a></i>                <p><a href=\"/data/news_"+str(seo_list[37][2])+"/index.html\" title=\"" + seo_list[37][0]  + "\" target=\"_blank\">" + seo_list[37][0]  + "</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"/data/news_"+str(seo_list[38][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[38][0]  + "\">" + seo_list[38][0]  + "</a></li>"
    html +="<li>· <a href=\"/data/news_"+str(seo_list[39][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[39][0]  + "\">" + seo_list[39][0]  + "</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>今日要闻</b>"
    html +="<a href=\"/data/news_"+str(seo_list[70][2])+"/index.html\" target=\"_blank\" class=\"more\">>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[27][2])+"/index.html\" title=\"" + seo_list[27][0]  + "\" target=\"_blank\">" + seo_list[27][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[28][2])+"/index.html\" title=\"" + seo_list[28][0]  + "\" target=\"_blank\">" + seo_list[28][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[29][2])+"/index.html\" title=\"" + seo_list[29][0]  + "\" target=\"_blank\">" + seo_list[29][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[30][2])+"/index.html\" title=\"" + seo_list[30][0]  + "\" target=\"_blank\">" + seo_list[30][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[31][2])+"/index.html\" title=\"" + seo_list[31][0]  + "\" target=\"_blank\">" + seo_list[31][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[32][2])+"/index.html\" title=\"" + seo_list[32][0]  + "\" target=\"_blank\">" + seo_list[32][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[33][2])+"/index.html\" title=\"" + seo_list[33][0]  + "\" target=\"_blank\">" + seo_list[33][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[34][2])+"/index.html\" title=\"" + seo_list[34][0]  + "\" target=\"_blank\">" + seo_list[34][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[35][2])+"/index.html\" title=\"" + seo_list[35][0]  + "\" target=\"_blank\">" + seo_list[35][0]  + "</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"/data/news_"+str(seo_list[36][2])+"/index.html\" title=\"" + seo_list[36][0]  + "\" target=\"_blank\">" + seo_list[36][0]  + "</a></p><span>6-06</span></li>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>比分网</b>"
    html +="<a href=\"/data/news_"+str(seo_list[71][2])+"/index.html\" target=\"_blank\" class=\"more\">>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\"><ul class=\"a\">"
    html +="<i><a href=\"/data/news_"+str(seo_list[40][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[40][0]  + "\"><img src=\"http://i3.sinaimg.cn/home/2013/0608/U8075P30DT20130608055803.jpg\" ></a></i>                <p><a href=\"/data/news_"+str(seo_list[40][2])+"/index.html\" title=\"" + seo_list[40][0]  + "\" target=\"_blank\">" + seo_list[40][0]  + "</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"/data/news_"+str(seo_list[41][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[41][0]  + "\">" + seo_list[41][0]  + "</a></li>"
    html +="<li>· <a href=\"/data/news_"+str(seo_list[42][2])+"/index.html\" target=\"_blank\" title=\"" + seo_list[42][0]  + "\">" + seo_list[42][0]  + "</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<div class=\"B9 gcopyright\">"
    html +="<ul>"
    html +="<a href=\"http://www.sportscn.com/aboutus/\" target=\"_blank\">关于华体</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/ad.html\" target=\"_blank\">广告服务</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/job.html\" target=\"_blank\">招聘信息</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/legal.html\" target=\"_blank\">法律声明</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/contact.html\" target=\"_blank\">联系我们</a>"
    html +="<a href=\"http://www.sportslink.com.cn/\"  target=\"_blank\" class=\"r\">体育网址大全</a>"
    html +="</ul>"
    html +="<dl>"
    html +="&copy;2000-<script>var date=new Date();document.write(date.getFullYear());</script> <a href=\"http://www.sportscn.com\">华体网</a> 版权所有 <a href=\"http://www.sportscn.com/aboutus/aboutus4.htm\" target=\"_blank\">文网文[2005]016号</a> 沪ICP备10022738号"
    html +="</dl>"
    html +="</div>"
    html +="</body>"
    html +="</html>"
    return html


def index_getHtml(html_tmp):
    html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
    html +="<html xmlns=\"http://www.w3.org/1999/xhtml\">"
    html +="<head>"
    html +="<title>BA_NBA_花边新闻_足球NBA比分_华体网</title>"
    html +="<META content=\"text/html; charset=utf-8\" http-equiv=Content-Type>"
    html +="<META content=IE=7 http-equiv=X-UA-Compatible>"
    html +="<META name=keywords content=\"NBA,资讯 花边新闻,娱乐新闻,篮球NBA,足球比分,体育新闻,欧洲杯,奥运会,赛事分析,比分直播,网球,高尔夫,潜水,国足,即时赔率指数,资料库,推介,心水,美女,图库,论坛\"/>"
    html +="<META name=description content=\"NBA NBA,资讯 华体网是面向全球中文用户的时尚体育社区，为广大体育爱好者提供资讯、足球及时比分赔率、篮球NBA赛事数据、互动社区、博客、相册、论坛、圈子、约球、百科、球场预订等服务\"/>"
    html +="<META content=0 http-equiv=Expires>"
    html +="<META content=no-cache http-equiv=Cache-Control>"
    html +="<META content=no-cache http-equiv=Pragma>"
    html +="<META name=MSSmartTagsPreventParsing content=True>"
    html +="<META content=Yes http-equiv=MSThemeCompatible>"
    html +="<link href=\"http://image.sportscn.com/2010/css/news.css\" type=\"text/css\" rel=\"stylesheet\" />"
    html +="</head>"
    html +="<body>"
    html +="<div class=\"B9 gtop\">"
    html +="<a href=\"http://www.sportscn.com/\" class=\"a\"></a>"
    html +="<ul>"
    html +="<ol>"
    html +="<a href=\"http://news.sportscn.com\" target=\"_blank\" class=\"b\"></a>"
    html +="<a href=\"http://football.sportscn.com\" target=\"_blank\"></a>"
    html +="<a href=\"http://basketball.sportscn.com/\" target=\"_blank\">NBA</a>"
    html +="<a href=\"http://football.sportscn.com/china\" target=\"_blank\"></a>"
    html +="<a href=\"http://golf.sportscn.com\" target=\"_blank\">高尔夫</a>"
    html +="<a href=\"http://tennis.sportscn.com/\" target=\"_blank\" >网球</a>"
    html +="<a href=\"http://othersport.sportscn.com/\" target=\"_blank\">综合</a>"
    html +="<a href=\"http://saiche.sportscn.com/\" target=\"_blank\" class=\"r\">赛车</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol>"
    html +="<a href=\"http://scripts1.sportscn.com/competition.do\" target=\"_blank\" class=\"b\">数据</a>"
    html +="<a href=\"http://live.sportscn.com\" target=\"_blank\">比分</a>"
    html +="<a href=\"http://odds.sportscn.com\" target=\"_blank\">指数</a>"
    html +="<a href=\"http://scripts.sportscn.com/odds/odds_calendar.php?encode=BIG5\" target=\"_blank\" class=\"r\">赛程</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol>"
    html +="<a href=\"http://v.sportscn.com\" target=\"_blank\" class=\"b\">视频</a>"
    html +="<a href=\"http://guess.sportscn.com\" target=\"_blank\">竞猜</a>"
    html +="<a href=\"http://caipiao.sportscn.com\" target=\"_blank\"class=\"r\">足彩</a>"
    html +="</ol>"
    html +="<p></p>"
    html +="<ol class=\"c\">"
    html +="<a href=\"http://club.sportscn.com\"  target=\"_blank\"class=\"b\">社区</a>"
    html +="<a href=\"http://shop.sportscn.com\"  target=\"_blank\">商城</a>"
    html +="<a href=\"http://bbs.sportscn.com\"  target=\"_blank\">论坛</a>"
    html +="<a href=\"http://ask.sportscn.com\"  target=\"_blank\" class=\"r\">百科</a>"
    html +="</ol>"
    html +="</ul>"
    html +="<dl></dl>"
    html +="</div>"
    html +="<div class=\"B9 ads\" style=\"position:static;\">"
    html +="<ul><img src=\"http://image.sportscn.com/2010/images/logonews.gif\">"
    html +="</div>"
    html +="<div class=\"B9\">"
    html +="<DIV class=newsleft><DIV class=nso>"
    html +="<DIV class=fm><FONT size=+0>您的位置：<A href=\"http://www.sportscn.com\">华体网</A> &gt;&gt; <A href=\"http://we.sportscn.com/category-3.html\">国际足球</A> &gt;&gt; 详细内容</FONT> <I class=l></I><I class=r></I>"
    html +="<DL></DL></DIV>"
    html +="<DIV style=\"PADDING-BOTTOM: 20px; PADDING-LEFT: 25px; PADDING-RIGHT: 25px; BACKGROUND: #fff; PADDING-TOP: 20px; _width: 586px\" class=fm_b2>"
    html +="<DIV class=pages>"
    html +="<DIV><STRONG>1</STRONG><A href=\"index2.html\">2</A><A href=\"index3.html\">3</A><A href=\"index4.html\">4</A><A href=\"index5.html\">5</A><A href=\"index6.html\">6</A><A href=\"index7.html\">7</A><A href=\"index8.html\">8</A><A href=\"index9.html\">9</A><A href=\"index10.html\">10</A></DIV></DIV>"
    html +="<DIV class=\"CleanBoth \"></DIV>"
    html += html_tmp
    html +="<DIV class=\"CleanBoth \"></DIV>"
    html +="<DIV class=pages>"
    html +="<DIV><STRONG>1</STRONG><A href=\"index2.html\">2</A><A href=\"index3.html\">3</A><A href=\"index4.html\">4</A><A href=\"index5.html\">5</A><A href=\"index6.html\">6</A><A href=\"index7.html\">7</A><A href=\"index8.html\">8</A><A href=\"index9.html\">9</A><A href=\"index10.html\">10</A></DIV></DIV></DIV>"
    html +="<DIV class=fm_footer><I class=l></I><I class=r></I></DIV></DIV></DIV>"
    html +="<div class=\"newsright\">"
    html +="<div class=\"srarch\">"
    html +="<div class=\"fm_red\">"
    html +="<a class=\"a1\"></a>"
    html +="<a class=\"a2\"></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i>"
    html +="</div>"
    html +="<div class=\"fm_b1\"></div>"
    html +="<div class=\"fm_b2\">"
    html +="<form action=\"http://www.google.cn/cse\" method=\"get\" target=\"_blank\" accept-charset=\"utf-8\" onsubmit=\"document.charset='utf-8';\" >"
    html +="<input type=\"hidden\" name=\"cx\" value=\"010816402563258067434:8qugcc2j5dw\" />"
    html +="<input name=\"hl\" value=\"zh-CN\" type=\"hidden\">"
    html +="<input name=\"ie\" value=\"UTF-8\" type=\"hidden\">"
    html +="<select name1=\"searchtxt\" class=\"b1\" id=\"searchtxt\" onchange=\"changetype();\">"
    html +="<option value=\"标题\">标题</option>"
    html +="<option value=\"内容\">内容</option>"
    html +="<option value=\"作者\">作者</option>"
    html +="</select>"
    html +="<input onfocus=\"if( this.value=='请输入关键字') {this.value='' };\" name=\"q\" id=\"query\" value=\"请输入关键字\" type=\"text\" class=\"b2\"/>"
    html +="<input type=\"image\" src=\"http://image.sportscn.com/2010/images/btn.gif\" class=\"b3\" value=\"搜索\" name=\"searchbtn\">"
    html +="</form>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>赛事前瞻</b>"
    html +="<a href=\"http://live.sportscn.com/news.html\" target=\"_blank\" class=\"more\">更多>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205359.html\" title=\"乌拉圭 VS 法国_\" target=\"_blank\">乌拉圭 VS 法国_</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205344.html\" title=\"幼狮食「意粉」\" target=\"_blank\">幼狮食「意粉」</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205343.html\" title=\"牙擦苏擒高卢鸡\" target=\"_blank\">牙擦苏擒高卢鸡</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205178.html\" title=\"日本逼和澳洲晋决赛周\" target=\"_blank\">日本逼和澳洲晋决赛周</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205175.html\" title=\"英格兰忌大“意”\" target=\"_blank\">英格兰忌大“意”</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205142.html\" title=\"世界杯报料：马拉维 vs 纳米比亚\" target=\"_blank\">世界杯报料：马拉维 vs 纳米比亚</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-205141.html\" title=\"友谊赛报料：乌拉圭 vs 法国\" target=\"_blank\">友谊赛报料：乌拉圭 vs 法国</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-204932.html\" title=\"太阳拆局(世盃外)\" target=\"_blank\">太阳拆局(世盃外)</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-204878.html\" title=\"太极虎出柙作客「黎」料\" target=\"_blank\">太极虎出柙作客「黎」料</a></li>"
    html +="<li>·<a href=\"http://nb.sportscn.com/viewlive-204877.html\" title=\"墨西哥实食无黐「牙」\" target=\"_blank\">墨西哥实食无黐「牙」</a></li>"
    html +="</ul>"
    html +="</div><div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>互动推荐</b>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul class=\"a\">"
    html +="<i><a href=\"http://bbs.sportscn.com/thread-174716-1-1.html\" target=\"_blank\" title=\"老贝情妇裸身钢管舞\"  ><img src=\"http://img.sportscn.com/crop?w=110&h=110&q=http://bbs.sportscn.com/attachments/month_1305/130509152411cce2785438a3f0.jpg\" ></a></i>                <p><a href=\"http://bbs.sportscn.com/thread-174716-1-1.html\" title=\"老贝情妇裸身钢管舞\" target=\"_blank\">老贝情妇裸身钢管舞</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"http://bbs.sportscn.com/thread-174716-1-1.html\" target=\"_blank\" title=\"老贝情妇裸身钢管舞\">老贝情妇裸身钢管舞</a></li>"
    html +="<li>· <a href=\"http://bbs.sportscn.com/thread-174476-1-1.html\" target=\"_blank\" title=\"英超宝贝豪乳撑爆比基尼 半裸背影股沟诱人(图)\">英超宝贝豪乳撑爆比...</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr zxgx\">"
    html +="<div class=\"fm\">"
    html +="<b>今日要闻</b>"
    html +="<a href=\"category-139.html\" target=\"_blank\" class=\"more\">更多>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\">"
    html +="<ul>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318936.html\" title=\"曼联2500万截温格猎物替鲁尼 1700万购未来班底\" target=\"_blank\">曼联2500万截温格猎物替鲁尼 1700万购未&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318931.html\" title=\"前瞻：詹皇复仇剧上演！ 邓肯统治热火内线？\" target=\"_blank\">前瞻：詹皇复仇剧上演！ 邓肯统治热火内&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318928.html\" title=\"6月5日转会综述：穆帅清洗马塔 拜仁罗本换苏神\" target=\"_blank\">6月5日转会综述：穆帅清洗马塔 拜仁罗本&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318929.html\" title=\"英超年收入已超30亿镑 55亿天价新约望再飙新高\" target=\"_blank\">英超年收入已超30亿镑 55亿天价新约望再&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318925.html\" title=\"法媒曝瓦罗和马赛商谈转会 今年夏天欲重返法甲\" target=\"_blank\">法媒曝瓦罗和马赛商谈转会 今年夏天欲重&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318921.html\" title=\"韦德：第一冠已倾其所有 卫冕着实比去年困难\" target=\"_blank\">韦德：第一冠已倾其所有 卫冕着实比去年&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318920.html\" title=\"墨西哥联合会杯23人出炉 曼联神锋领衔攻击线\" target=\"_blank\">墨西哥联合会杯23人出炉 曼联神锋领衔攻&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318919.html\" title=\"尤文图斯本土球迷数量居榜首 米兰双雄难分伯仲\" target=\"_blank\">尤文图斯本土球迷数量居榜首 米兰双雄难&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318908.html\" title=\"曝尤文已锁定野兽特维斯 税后年薪700万合同3年\" target=\"_blank\">曝尤文已锁定野兽特维斯 税后年薪700万&nbsp;</a></p><span>6-06</span></li>"
    html +="<li><p>·<a href=\"http://we.sportscn.com/viewnews-1318906.html\" title=\"吴克群力挺科比讥讽詹姆斯 挖苦詹皇假摔演技高\" target=\"_blank\">吴克群力挺科比讥讽詹姆斯 挖苦詹皇假摔&nbsp;</a></p><span>6-06</span></li>"
    html +="</ul>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="<div class=\"nmr hdtj\">"
    html +="<div class=\"fm\">"
    html +="<b>博客</b>"
    html +="<a href=\"http://club.sportscn.com/space.php?do=blog&view=all&orderby=dateline\" target=\"_blank\" class=\"more\">更多>></a>"
    html +="<i class=\"l\"></i><i class=\"r\"></i><dl></dl>"
    html +="</div>"
    html +="<div class=\"fm_b2\"><ul class=\"a\">"
    html +="<i><a href=\"http://club.sportscn.com/space-221012-do-blog-id-134191.html\" target=\"_blank\" title=\"比基尼小姐大赛 众美女穿性感泳装玩拳击\"><img src=\"http://img.sportscn.com/crop?w=110&h=110&q=http://club.sportscn.com/attachment/201306/3/221012_1370229565hnyp.jpg\" ></a></i>                <p><a href=\"http://club.sportscn.com/space-221012-do-blog-id-134191.html\" title=\"比基尼小姐大赛 众美女穿性感泳装玩拳击\" target=\"_blank\">比基尼小姐大赛 众美女穿性感泳装玩拳击</a> </p>"
    html +="</ul>"
    html +="<ul class=\"b\"><li>· <a href=\"http://club.sportscn.com/space-221012-do-blog-id-134191.html\" target=\"_blank\" title=\"比基尼小姐大赛 众美女穿性感泳装玩拳击\">比基尼小姐大赛 众美女穿性感泳装玩拳击</a></li>"
    html +="<li>· <a href=\"http://club.sportscn.com/space-221012-do-blog-id-134190.html\" target=\"_blank\" title=\"英超女神凯莉布鲁克为GQ拍摄全裸写真\">英超女神凯莉布鲁克为GQ拍摄全裸写真</a></li>"
    html +="</ul>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="</div>"
    html +="<div class=\"fm_footer\"><i class=\"l\"></i><i class=\"r\"></i></div>"
    html +="</div>"
    html +="</div>"
    html +="</div>"
    html +="<div class=\"CleanBoth\"></div>"
    html +="<div class=\"B9 gcopyright\">"
    html +="<ul>"
    html +="<a href=\"http://www.sportscn.com/aboutus/\" target=\"_blank\">关于华体</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/ad.html\" target=\"_blank\">广告服务</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/job.html\" target=\"_blank\">招聘信息</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/legal.html\" target=\"_blank\">法律声明</a>"
    html +="<a href=\"http://www.sportscn.com/aboutus/contact.html\" target=\"_blank\">联系我们</a>"
    html +="<a href=\"http://www.sportslink.com.cn/\"  target=\"_blank\" class=\"r\">体育网址大全</a>"
    html +="</ul>"
    html +="<dl>"
    html +="&copy;2000-<script>var date=new Date();document.write(date.getFullYear());</script> <a href=\"http://www.sportscn.com\">华体网</a> 版权所有 <a href=\"http://www.sportscn.com/aboutus/aboutus4.htm\" target=\"_blank\">文网文[2005]016号</a> 沪ICP备10022738号"
    html +="</dl>"
    html +="</div>"
    html +="</body>"
    html +="</html>"
    return html